import type { Product, DeveloperBuild, BuildingBlock, RecentItem } from "@/constants/types"
import { TIER } from "@/constants/tiers"

export const TRENDING_PRODUCTS: Product[] = [
  {
    id: "1",
    rank: 1,
    name: "MeetWave",
    tagline: "Privacy-first AI meeting recorder for Windows",
    comments: 24,
    tags: ["AI", "Productivity"],
    upvotes: 1245,
    builds: 142,
    logo: { text: "|||", bgColor: "bg-slate-900", textColor: "text-blue-400" },
  },
  {
    id: "2",
    rank: 2,
    name: "Dreamstate",
    tagline: "AI Head of Growth Agents Across Every Channel",
    comments: 18,
    tags: ["Marketing", "AI", "Productivity"],
    upvotes: 982,
    builds: 98,
    logo: { text: "DS", bgColor: "bg-slate-800", textColor: "text-teal-400" },
  },
  {
    id: "3",
    rank: 3,
    name: "Isometric Studio",
    tagline: "Create isometric illustrations fast",
    comments: 42,
    tags: ["Design Resources", "SaaS", "Other"],
    upvotes: 754,
    builds: 76,
    logo: { text: "ISO", bgColor: "bg-white", textColor: "text-slate-800", borderColor: "border border-slate-200" },
  },
  {
    id: "4",
    rank: 4,
    name: "Distro",
    tagline: "AI distribution operator for content, conversations, outreach, and pipeline.",
    comments: 12,
    tags: ["Marketing", "SaaS", "SEO Tools"],
    upvotes: 412,
    builds: 54,
    logo: { text: "D", bgColor: "bg-indigo-500", textColor: "text-white" },
  },
  {
    id: "5",
    rank: 5,
    name: "Supernova",
    tagline: "Design system manager for scaling UI components.",
    comments: 38,
    tags: ["Design Tools", "SaaS"],
    upvotes: 389,
    builds: 112,
    logo: { text: "SN", bgColor: "bg-pink-500", textColor: "text-white" },
  },
  {
    id: "6",
    rank: 6,
    name: "Orbit",
    tagline: "Community growth platform for DevRel teams.",
    comments: 21,
    tags: ["Marketing", "DevTools"],
    upvotes: 310,
    builds: 89,
    logo: { text: "O", bgColor: "bg-purple-600", textColor: "text-white" },
  },
  {
    id: "7",
    rank: 7,
    name: "FluxAI",
    tagline: "Generative AI for fast PCB design and engineering.",
    comments: 54,
    tags: ["AI", "Engineering"],
    upvotes: 295,
    builds: 134,
    logo: { text: "FX", bgColor: "bg-emerald-500", textColor: "text-slate-900" },
  },
  {
    id: "8",
    rank: 8,
    name: "CodeSense",
    tagline: "Context-aware code review assistant.",
    comments: 47,
    tags: ["Developer Tools", "AI"],
    upvotes: 278,
    builds: 201,
    logo: { text: "CS", bgColor: "bg-slate-900", textColor: "text-sky-400" },
  },
  {
    id: "9",
    rank: 9,
    name: "Synthetix",
    tagline: "Generate synthetic user data for safe testing.",
    comments: 15,
    tags: ["Data", "Privacy"],
    upvotes: 241,
    builds: 67,
    logo: { text: "SY", bgColor: "bg-orange-500", textColor: "text-white" },
  },
  {
    id: "10",
    rank: 10,
    name: "Velocity",
    tagline: "High-performance edge caching for Next.js.",
    comments: 32,
    tags: ["Infrastructure", "Performance"],
    upvotes: 210,
    builds: 145,
    logo: { text: "V", bgColor: "bg-blue-600", textColor: "text-white" },
  },
  {
    id: "11",
    rank: 11,
    name: "Loomis",
    tagline: "AI-powered video translation and dubbing.",
    comments: 63,
    tags: ["Video", "AI"],
    upvotes: 198,
    builds: 42,
    logo: { text: "LM", bgColor: "bg-rose-500", textColor: "text-white" },
  },
  {
    id: "12",
    rank: 12,
    name: "Sentinel",
    tagline: "Automated cloud security posture management.",
    comments: 11,
    tags: ["Security", "Cloud"],
    upvotes: 185,
    builds: 88,
    logo: { text: "ST", bgColor: "bg-slate-800", textColor: "text-amber-400" },
  },
  {
    id: "13",
    rank: 13,
    name: "Nexus",
    tagline: "Unified API for all your SaaS integrations.",
    comments: 42,
    tags: ["API", "Infrastructure"],
    upvotes: 164,
    builds: 110,
    logo: { text: "NX", bgColor: "bg-cyan-600", textColor: "text-white" },
  },
  {
    id: "14",
    rank: 14,
    name: "Prism",
    tagline: "Beautiful analytics dashboards for Stripe.",
    comments: 29,
    tags: ["Analytics", "Finance"],
    upvotes: 142,
    builds: 55,
    logo: { text: "PR", bgColor: "bg-violet-600", textColor: "text-white" },
  },
]

export const DEVELOPER_BUILDS: DeveloperBuild[] = [
  { name: "Nexus", desc: "AI research workspace for teams and individuals.", builtWith: ["Dodo", "Supabase", "Vercel"], views: 124, likes: 36, logo: "NX", logoBg: "bg-slate-900 text-cyan-400", tier: TIER.PREMIUM_PLUS },
  { name: "InvoiceAI", desc: "Automated invoicing for freelancers.", builtWith: ["Stripe", "PostHog", "Resend"], views: 98, likes: 28, logo: "IA", logoBg: "bg-indigo-100 text-indigo-500", tier: TIER.PREMIUM },
  { name: "ShipFast", desc: "SaaS boilerplate to launch faster with best practices.", builtWith: ["Supabase", "Next.js", "Tailwind"], views: 76, likes: 21, logo: "SF", logoBg: "bg-teal-500 text-white", tier: TIER.PREMIUM_PLUS },
  { name: "NoteFlow", desc: "AI note taking app for busy professionals.", builtWith: ["OpenAI", "Pinecone", "Vercel"], views: 62, likes: 19, logo: "NF", logoBg: "bg-rose-100 text-rose-500", tier: TIER.FREE },
]

export const BUILDING_BLOCKS: BuildingBlock[] = [
  { name: "Supabase", builds: 82, category: "Database - BaaS", logo: "⚡", logoBg: "bg-emerald-100 text-emerald-500", tier: TIER.PREMIUM_PLUS },
  { name: "Stripe", builds: 71, category: "Payments - Billing", logo: "S", logoBg: "bg-indigo-500 text-white", tier: TIER.PREMIUM },
  { name: "Vercel", builds: 68, category: "Hosting - Edge", logo: "▲", logoBg: "bg-black text-white", tier: TIER.PREMIUM_PLUS },
  { name: "Dodo Payments", builds: 37, category: "Payments - API", logo: "D", logoBg: "bg-purple-500 text-white", tier: TIER.FREE },
  { name: "PostHog", builds: 34, category: "Analytics - Open Source", logo: "🦔", logoBg: "bg-amber-100 text-amber-500", tier: TIER.FREE },
  { name: "Resend", builds: 29, category: "Email - API", logo: "R", logoBg: "bg-black text-white", tier: TIER.FREE },
]

export const RECENTLY_ADDED: RecentItem[] = [
  { name: "BetterAuth", desc: "Auth that just works for modern apps", category: "Auth", logo: "A", logoBg: "bg-black text-white", tier: TIER.PREMIUM },
  { name: "QStash", desc: "Serverless message queues", category: "Infra", logo: "Q", logoBg: "bg-sky-100 text-sky-500", tier: TIER.PREMIUM_PLUS },
  { name: "TinyBase", desc: "Local-first, open source database", category: "Database", logo: "T", logoBg: "bg-orange-100 text-orange-500", tier: TIER.FREE },
  { name: "Uploadthing", desc: "File uploads for the modern web", category: "Dev Tools", logo: "U", logoBg: "bg-purple-100 text-purple-500", tier: TIER.FREE },
  { name: "Mailsend", desc: "Developer friendly email API", category: "Email", logo: "M", logoBg: "bg-orange-500 text-white", tier: TIER.FREE },
  { name: "PGlite", desc: "SQLite for Postgres developers", category: "Database", logo: "P", logoBg: "bg-slate-100 text-slate-500", tier: TIER.FREE },
]
