export const ROUTES = {
  HOME: "/",
  DISCOVER_NEW_RISING: "/discover/new-rising",
  DISCOVER_RISING_TOOLS: "/discover/rising-tools",
  DISCOVER_RISING_PRODUCTS: "/discover/rising-products",
  DISCOVER_RECENTLY_ADDED: "/discover/recently-added",
  DISCOVER_POPULAR_BUILDING_BLOCKS: "/discover/popular-building-blocks",
  DISCOVER_WEEKLY_LAUNCHES: "/discover/weekly-launches",
  DISCOVER_DAILY_LAUNCHES: "/discover/daily-launches",
  TRENDING: "/trending",
  PRICING: "/pricing",
  SUBMIT: "/submit",
  SHOWCASE: "/showcase",
  SHOWCASE_TOOL: (toolSlug: string) => `/showcase?tool=${encodeURIComponent(toolSlug)}`,
  PRODUCTS: "/products",
  PRODUCT: (slug: string) => `/products/${slug}`,
  TOOLS: "/tools",
  TOOL: (slug: string) => `/tools/${slug}`,
  PRIVACY: "/privacy",
  TERMS: "/terms",
  REFUND: "/refund",
  FAQ: "/faq",
  DASHBOARD: "/dashboard",
  DASHBOARD_PROFILE: "/dashboard/profile",
  MAKERS: "/makers",
  MAKER: (username: string) => `/makers/${username}`,
} as const
