export const ROUTES = {
  HOME: "/",
  DISCOVER_POPULAR_BUILDING_BLOCKS: "/discover/popular-building-blocks",
  DISCOVER_WEEKLY_LAUNCHES: "/discover/weekly-launches",
  TRENDING: "/trending",
  PRICING: "/pricing",
  SUBMIT: "/submit",
  SUBMIT_PRODUCT: "/submit?type=product",
  SUBMIT_TOOL: "/submit?type=tool",
  SUBMIT_PRODUCT_WITH_TOOL: (toolSlug: string) =>
    `/submit?type=product&tool=${encodeURIComponent(toolSlug)}`,
  SHOWCASE: "/submit?type=product",
  SHOWCASE_TOOL: (toolSlug: string) =>
    `/submit?type=product&tool=${encodeURIComponent(toolSlug)}`,
  PRODUCTS: "/products",
  PRODUCT: (slug: string) => `/products/${slug}`,
  TOOLS: "/tools",
  TOOL: (slug: string) => `/tools/${slug}`,
  TOOL_CATEGORY: (slug: string) => `/tools/category/${encodeURIComponent(slug)}`,
  ALTERNATIVES: (slug: string) => `/alternatives/${encodeURIComponent(slug)}`,
  PRODUCTHUNT_ALTERNATIVE: "/producthunt-alternative",
  UNEED_ALTERNATIVE: "/uneed-alternative",
  MICROLAUNCH_ALTERNATIVE: "/microlaunch-alternative",
  BETALIST_ALTERNATIVE: "/betalist-alternative",
  COMPARE: (slug: string) => `/compare/${encodeURIComponent(slug)}`,
  BUILT_WITH: (slug: string) => `/built-with/${encodeURIComponent(slug)}`,
  PRIVACY: "/privacy",
  TERMS: "/terms",
  REFUND: "/refund",
  FAQ: "/faq",
  DASHBOARD: "/dashboard",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_PRODUCT_EDIT: (slug: string) =>
    `/dashboard/products/${encodeURIComponent(slug)}/edit`,
  DASHBOARD_PRODUCT_ANALYTICS: (slug: string) =>
    `/dashboard/products/${encodeURIComponent(slug)}/analytics`,
  DASHBOARD_TOOLS: "/dashboard/tools",
  DASHBOARD_TOOL_EDIT: (slug: string) =>
    `/dashboard/tools/${encodeURIComponent(slug)}/edit`,
  DASHBOARD_TOOL_ANALYTICS: (slug: string) =>
    `/dashboard/tools/${encodeURIComponent(slug)}/analytics`,
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  DASHBOARD_PROFILE: "/dashboard/profile",
  MAKERS: "/makers",
  MAKER: (username: string) => `/makers/${username}`,
  CHECKOUT_SUCCESS: "/",
  CHECKOUT_CANCEL: "/pricing",
} as const
