export const ROUTES = {
  HOME: "/",
  DISCOVER_POPULAR_BUILDING_BLOCKS: "/discover/popular-building-blocks",
  DISCOVER_WEEKLY_LAUNCHES: "/discover/weekly-launches",
  TRENDING: "/trending",
  PRICING: "/pricing",
  SUBMIT: "/submit",
  SHOWCASE: "/showcase",
  SHOWCASE_TOOL: (toolSlug: string) => `/showcase?tool=${encodeURIComponent(toolSlug)}`,
  PRODUCTS: "/products",
  PRODUCT: (slug: string) => `/products/${slug}`,
  TOOLS: "/tools",
  TOOL: (slug: string) => `/tools/${slug}`,
  PRIVACY: "/privacy",
  TERMS: "/terms",
  REFUND: "/refund",
  FAQ: "/faq",
  DASHBOARD: "/dashboard",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_PRODUCT_EDIT: (slug: string) =>
    `/dashboard/products/${encodeURIComponent(slug)}/edit`,
  DASHBOARD_PRODUCT_ANALYTICS: (slug: string) =>
    `/dashboard/products/${encodeURIComponent(slug)}/analytics`,
  DASHBOARD_TOOLS: "/dashboard/tools",
  DASHBOARD_TOOL_EDIT: (slug: string) =>
    `/dashboard/tools/${encodeURIComponent(slug)}/edit`,
  DASHBOARD_TOOL_ANALYTICS: (slug: string) =>
    `/dashboard/tools/${encodeURIComponent(slug)}/analytics`,
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  DASHBOARD_PROFILE: "/dashboard/profile",
  MAKERS: "/makers",
  MAKER: (username: string) => `/makers/${username}`,
  CHECKOUT_SUCCESS: "/",
  CHECKOUT_CANCEL: "/pricing",
} as const
