const CRAWLER_PATTERNS = [
  "googlebot",
  "bingbot",
  "slurp",
  "duckduckbot",
  "baiduspider",
  "yandexbot",
  "sogou",
  "exabot",
  "facebot",
  "facebookexternalhit",
  "ia_archiver",
  "twitterbot",
  "linkedinbot",
  "embedly",
  "quora link preview",
  "showyoubot",
  "outbrain",
  "pinterest",
  "slackbot",
  "vkshare",
  "w3c_validator",
  "redditbot",
  "applebot",
  "whatsapp",
  "flipboard",
  "tumblr",
  "bitlybot",
  "skypeuripreview",
  "nuzzel",
  "discordbot",
  "google page speed",
  "qwantify",
  "bitrix link preview",
  "xing-content",
  "chrome-lighthouse",
  "telegrambot",
  // AI Bots & LLM Answer Engines
  "gptbot",
  "chatgpt-user",
  "oai-searchbot",
  "claudebot",
  "claude-web",
  "anthropic-ai",
  "perplexitybot",
  "google-extended",
  "googleother",
  "applebot-extended",
  "amazonbot",
  "cohere-ai",
  "meta-externalagent",
  "bytespider",
  "ccbot",
  "diffbot",
  "youbot",
  "deepseekbot",
  "timpibot",
  "mistralai-crawler",
]

export const isCrawler = (userAgent: string | null | undefined): boolean => {
  if (!userAgent) return false
  const ua = userAgent.toLowerCase()
  return CRAWLER_PATTERNS.some((pattern) => ua.includes(pattern))
}
